using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.0.90
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------













namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Generic Content</summary>
	[PublishedContentModel("GenericContent")]
	public partial class GenericContent : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "GenericContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GenericContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GenericContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return this.GetPropertyValue<IHtmlString>("content"); }
		}
	}

	/// <summary>Numeric Types</summary>
	[PublishedContentModel("NumericTypes")]
	public partial class NumericTypes : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "NumericTypes";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NumericTypes(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NumericTypes, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Bool
		///</summary>
		[ImplementPropertyType("bool")]
		public bool Bool
		{
			get { return this.GetPropertyValue<bool>("bool"); }
		}

		///<summary>
		/// Byte
		///</summary>
		[ImplementPropertyType("byte")]
		public int Byte
		{
			get { return this.GetPropertyValue<int>("byte"); }
		}

		///<summary>
		/// Decimal
		///</summary>
		[ImplementPropertyType("decimal")]
		public string Decimal
		{
			get { return this.GetPropertyValue<string>("decimal"); }
		}

		///<summary>
		/// Double
		///</summary>
		[ImplementPropertyType("double")]
		public string Double
		{
			get { return this.GetPropertyValue<string>("double"); }
		}

		///<summary>
		/// Float
		///</summary>
		[ImplementPropertyType("float")]
		public string Float
		{
			get { return this.GetPropertyValue<string>("float"); }
		}

		///<summary>
		/// Int
		///</summary>
		[ImplementPropertyType("int")]
		public int Int
		{
			get { return this.GetPropertyValue<int>("int"); }
		}

		///<summary>
		/// Long
		///</summary>
		[ImplementPropertyType("long")]
		public string Long
		{
			get { return this.GetPropertyValue<string>("long"); }
		}

		///<summary>
		/// SByte
		///</summary>
		[ImplementPropertyType("sbyte")]
		public int Sbyte
		{
			get { return this.GetPropertyValue<int>("sbyte"); }
		}

		///<summary>
		/// Short
		///</summary>
		[ImplementPropertyType("short")]
		public int Short
		{
			get { return this.GetPropertyValue<int>("short"); }
		}

		///<summary>
		/// Slider
		///</summary>
		[ImplementPropertyType("slider")]
		public object Slider
		{
			get { return this.GetPropertyValue("slider"); }
		}

		///<summary>
		/// UInt
		///</summary>
		[ImplementPropertyType("uint")]
		public string Uint
		{
			get { return this.GetPropertyValue<string>("uint"); }
		}

		///<summary>
		/// ULong
		///</summary>
		[ImplementPropertyType("ulong")]
		public string Ulong
		{
			get { return this.GetPropertyValue<string>("ulong"); }
		}

		///<summary>
		/// UShort
		///</summary>
		[ImplementPropertyType("ushort")]
		public int Ushort
		{
			get { return this.GetPropertyValue<int>("ushort"); }
		}
	}

	/// <summary>Text Types</summary>
	[PublishedContentModel("TextTypes")]
	public partial class TextTypes : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "TextTypes";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TextTypes(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TextTypes, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Char
		///</summary>
		[ImplementPropertyType("char")]
		public string Char
		{
			get { return this.GetPropertyValue<string>("char"); }
		}

		///<summary>
		/// DropdownList
		///</summary>
		[ImplementPropertyType("dropdownlist")]
		public object Dropdownlist
		{
			get { return this.GetPropertyValue("dropdownlist"); }
		}

		///<summary>
		/// DropdownListPublishKeys
		///</summary>
		[ImplementPropertyType("dropdownlistpublishkeys")]
		public object Dropdownlistpublishkeys
		{
			get { return this.GetPropertyValue("dropdownlistpublishkeys"); }
		}

		///<summary>
		/// HtmlString
		///</summary>
		[ImplementPropertyType("htmlstring")]
		public string Htmlstring
		{
			get { return this.GetPropertyValue<string>("htmlstring"); }
		}

		///<summary>
		/// NoEdit
		///</summary>
		[ImplementPropertyType("noedit")]
		public string Noedit
		{
			get { return this.GetPropertyValue<string>("noedit"); }
		}

		///<summary>
		/// RadiobuttonList
		///</summary>
		[ImplementPropertyType("radiobuttonlist")]
		public object Radiobuttonlist
		{
			get { return this.GetPropertyValue("radiobuttonlist"); }
		}

		///<summary>
		/// RichText
		///</summary>
		[ImplementPropertyType("richText")]
		public IHtmlString RichText
		{
			get { return this.GetPropertyValue<IHtmlString>("richText"); }
		}

		///<summary>
		/// String
		///</summary>
		[ImplementPropertyType("string")]
		public string String
		{
			get { return this.GetPropertyValue<string>("string"); }
		}
	}

	/// <summary>Arrays</summary>
	[PublishedContentModel("Arrays")]
	public partial class Arrays : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Arrays";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Arrays(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Arrays, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// CheckboxList
		///</summary>
		[ImplementPropertyType("CheckboxList")]
		public object CheckboxList
		{
			get { return this.GetPropertyValue("CheckboxList"); }
		}

		///<summary>
		/// Dictionary Picker
		///</summary>
		[ImplementPropertyType("dictionaryPicker")]
		public string DictionaryPicker
		{
			get { return this.GetPropertyValue<string>("dictionaryPicker"); }
		}

		///<summary>
		/// DropDownListMultiple
		///</summary>
		[ImplementPropertyType("dropdownlistmultiple")]
		public object Dropdownlistmultiple
		{
			get { return this.GetPropertyValue("dropdownlistmultiple"); }
		}

		///<summary>
		/// DropDownListMultiplePublishKeys
		///</summary>
		[ImplementPropertyType("dropdownlistmultiplepublishkeys")]
		public object Dropdownlistmultiplepublishkeys
		{
			get { return this.GetPropertyValue("dropdownlistmultiplepublishkeys"); }
		}

		///<summary>
		/// IntArray
		///</summary>
		[ImplementPropertyType("intarray")]
		public string Intarray
		{
			get { return this.GetPropertyValue<string>("intarray"); }
		}

		///<summary>
		/// StaffList
		///</summary>
		[ImplementPropertyType("staffList")]
		public string StaffList
		{
			get { return this.GetPropertyValue<string>("staffList"); }
		}

		///<summary>
		/// StringArray
		///</summary>
		[ImplementPropertyType("stringarray")]
		public string Stringarray
		{
			get { return this.GetPropertyValue<string>("stringarray"); }
		}
	}

	/// <summary>Objects</summary>
	[PublishedContentModel("Objects")]
	public partial class Objects : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Objects";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Objects(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Objects, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// DateFromPicker
		///</summary>
		[ImplementPropertyType("datefrompicker")]
		public DateTime Datefrompicker
		{
			get { return this.GetPropertyValue<DateTime>("datefrompicker"); }
		}

		///<summary>
		/// DateFromText
		///</summary>
		[ImplementPropertyType("datefromtext")]
		public string Datefromtext
		{
			get { return this.GetPropertyValue<string>("datefromtext"); }
		}

		///<summary>
		/// MultiNodeTreePicker
		///</summary>
		[ImplementPropertyType("multinodetreepicker")]
		public string Multinodetreepicker
		{
			get { return this.GetPropertyValue<string>("multinodetreepicker"); }
		}
	}

	/// <summary>Person</summary>
	[PublishedContentModel("Person")]
	public partial class Person : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Person";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Person(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Person, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Favorite Locations
		///</summary>
		[ImplementPropertyType("favoriteLocations")]
		public object FavoriteLocations
		{
			get { return this.GetPropertyValue("favoriteLocations"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("name")]
		public string Name
		{
			get { return this.GetPropertyValue<string>("name"); }
		}

		///<summary>
		/// Photo
		///</summary>
		[ImplementPropertyType("photo")]
		public object Photo
		{
			get { return this.GetPropertyValue("photo"); }
		}

		///<summary>
		/// Primary Location
		///</summary>
		[ImplementPropertyType("primaryLocation")]
		public object PrimaryLocation
		{
			get { return this.GetPropertyValue("primaryLocation"); }
		}

		///<summary>
		/// Secondary Location
		///</summary>
		[ImplementPropertyType("secondaryLocation")]
		public object SecondaryLocation
		{
			get { return this.GetPropertyValue("secondaryLocation"); }
		}
	}

	/// <summary>Location</summary>
	[PublishedContentModel("Location")]
	public partial class Location : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Location";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Location(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Location, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("name")]
		public string Name
		{
			get { return this.GetPropertyValue<string>("name"); }
		}
	}

	/// <summary>Enums</summary>
	[PublishedContentModel("Enums")]
	public partial class Enums : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Enums";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Enums(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Enums, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Month
		///</summary>
		[ImplementPropertyType("month")]
		public string Month
		{
			get { return this.GetPropertyValue<string>("month"); }
		}
	}

	/// <summary>Blog Entry</summary>
	[PublishedContentModel("BlogEntry")]
	public partial class BlogEntry : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "BlogEntry";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogEntry(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogEntry, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return this.GetPropertyValue<IHtmlString>("content"); }
		}

		///<summary>
		/// Featured
		///</summary>
		[ImplementPropertyType("featured")]
		public bool Featured
		{
			get { return this.GetPropertyValue<bool>("featured"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public object Image
		{
			get { return this.GetPropertyValue("image"); }
		}

		///<summary>
		/// PostDate
		///</summary>
		[ImplementPropertyType("postdate")]
		public DateTime Postdate
		{
			get { return this.GetPropertyValue<DateTime>("postdate"); }
		}

		///<summary>
		/// Related Links
		///</summary>
		[ImplementPropertyType("relatedLinks")]
		public Newtonsoft.Json.Linq.JArray RelatedLinks
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JArray>("relatedLinks"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Blog Home</summary>
	[PublishedContentModel("BlogHome")]
	public partial class BlogHome : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "BlogHome";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BlogHome(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BlogHome, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// FeaturedBlogEntry
		///</summary>
		[ImplementPropertyType("featuredblogentry")]
		public object Featuredblogentry
		{
			get { return this.GetPropertyValue("featuredblogentry"); }
		}

		///<summary>
		/// SidebarCopy
		///</summary>
		[ImplementPropertyType("sidebarcopy")]
		public string Sidebarcopy
		{
			get { return this.GetPropertyValue<string>("sidebarcopy"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}

	/// <summary>Members</summary>
	[PublishedContentModel("Members")]
	public partial class Members : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Members";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Members(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Members, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Single Member
		///</summary>
		[ImplementPropertyType("singleMember")]
		public object SingleMember
		{
			get { return this.GetPropertyValue("singleMember"); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public object UmbracoFile
		{
			get { return this.GetPropertyValue("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public object UmbracoFile
		{
			get { return this.GetPropertyValue("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Age
		///</summary>
		[ImplementPropertyType("age")]
		public int Age
		{
			get { return this.GetPropertyValue<int>("age"); }
		}

		///<summary>
		/// First Name
		///</summary>
		[ImplementPropertyType("firstName")]
		public string FirstName
		{
			get { return this.GetPropertyValue<string>("firstName"); }
		}

		///<summary>
		/// Last Name
		///</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return this.GetPropertyValue<string>("lastName"); }
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
